"""add metrics to automl runs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 19:40:36.291987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("automl_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("metrics", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("automl_runs", schema=None) as batch_op:
        batch_op.drop_column("metrics")

    # ### end Alembic commands ###
